config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from healthapp import urls as healthurls
from healthAdmin import urls as dashboardurls
from doctorapp import urls as doctorurls
from patientapp import urls as patienturls
from doctorPanel import urls as docpanelurls

from rest_framework.routers import DefaultRouter
from healthapp.api.views import DoctorViewSet, PatientViewSet, PrescriptionViewSet

router = DefaultRouter()
router.register(r'doctors', DoctorViewSet)
router.register(r'patients', PatientViewSet)
router.register(r'prescriptions', PrescriptionViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('doctor/', include(healthurls, namespace='healthapp')),
    path('', include(dashboardurls, namespace='healthAdmin')),
    path('', include(docpanelurls, namespace='doctorPanel')),
    path('', include(doctorurls, namespace='doctorapp')),
    path('', include(patienturls, namespace='patientapp')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

healthapp/urls.py
from django.urls import path
from .views import AddPrescription,AllPrescription,ViewPrescription,UpdatePrescription,DeletePrescription


app_name='healthapp'

urlpatterns = [
    path('add-prescription', AddPrescription.as_view(), name="add_prescription"),
     path('all-prescription', AllPrescription.as_view(), name="all_prescription"),
    path('update-prescription/<int:pk>', UpdatePrescription.as_view(), name="update_prescription"),
    path('view-prescription/<int:pk>', ViewPrescription.as_view(), name="view_prescription"),
    path('delete-prescription/<int:pk>', DeletePrescription.as_view(), name="delete_prescription"),
    
]

healthapp/models.py
from django.db import models

from django.db import models

class Doctor(models.Model):
    doctor_id = models.CharField(max_length=255, default='d00x')
    doctor_name = models.CharField(max_length=255)
    doctor_designation = models.CharField(max_length=100)
    doctor_contact_number = models.CharField(max_length=15)

    def __str__(self):
        return self.doctor_name


class Patient(models.Model):
    PATIENT_CATEGORIES = [
        ('Inpatient', 'Inpatient'),
        ('Outpatient', 'Outpatient'),
        ('Pediatric', 'Pediatric'),
        ('Geriatric', 'Geriatric')
    ]
    patient_id = models.CharField(max_length=50,default='p00x')
    patient_name = models.CharField(max_length=255)
    age = models.PositiveIntegerField()
    gender = models.CharField(max_length=10)
    height = models.FloatField()
    weight = models.FloatField()
    patient_category = models.CharField(max_length=50, choices=PATIENT_CATEGORIES)
    doctor_id = models.ForeignKey(Doctor, on_delete=models.CASCADE, default=1) 
    contact_number = models.CharField(max_length=15)
    address = models.TextField()
    diagnostic_center = models.CharField(max_length=255)
    
    def __str__(self):
        return self.patient_name 

class Prescription(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    MEDICINE_NAME = [
        ('isoniazid', 'Isoniazid'),
        ('rifampin ', 'Rifampin '),
        ('pyrazinamide ', 'Pyrazinamide'),
         ('ethambutol', 'Ethambutol '),
        ('streptomycin ', 'Streptomycin'),
    ]
    drug_name = models.CharField(max_length=200,choices=MEDICINE_NAME)
    description = models.TextField(blank=True)
    TAKEN_SLOT = [
        ('morning', 'Morning'),
        ('midday', 'Midday'),
        ('night', 'Night'),
    ]
    taken_time1 = models.CharField(max_length=200, choices=TAKEN_SLOT,null=True,blank=True)
    taken_time2 = models.CharField(max_length=200, choices=TAKEN_SLOT,null=True,blank=True)
    taken_time3 = models.CharField(max_length=200, choices=TAKEN_SLOT,null=True,blank=True)
    start_date = models.DateField(null=True,blank=True)
    end_date = models.DateField(null=True,blank=True)

    def __str__(self):
        return f"{self.patient.patient_name}'s Prescription for {self.drug_name}"
    

    
    

healthapp/forms.py
from django import forms
from .models import Patient,Prescription,Doctor


class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = '__all__'
        widgets = {
            'doctor_id': forms.TextInput(attrs={'class': 'form-control'}),
            'doctor_name': forms.TextInput(attrs={'class': 'form-control'}),
            'doctor_designation': forms.TextInput(attrs={'class': 'form-control'}),
            'doctor_contact_number': forms.TextInput(attrs={'class': 'form-control'}),
        }
        

class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = '__all__'
        widgets = {
            'patient_id': forms.TextInput(attrs={'class': 'form-control'}),            
            'prescription_date': forms.TextInput(attrs={'class': 'form-control'}),
            'patient_name': forms.TextInput(attrs={'class': 'form-control'}),
            'age': forms.TextInput(attrs={'class': 'form-control'}),
            'gender': forms.TextInput(attrs={'class': 'form-control'}),
            'height': forms.TextInput(attrs={'class': 'form-control'}),
            'weight': forms.TextInput(attrs={'class': 'form-control'}),
            'patient_category': forms.Select(attrs={'class': 'form-control'}),
            'doctor_id': forms.Select(attrs={'class': 'form-control'}),
            'contact_number': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'diagnostic_center': forms.TextInput(attrs={'class': 'form-control'}),
        }


class PrescriptionForm(forms.ModelForm):
    class Meta:
        model = Prescription
        fields = '__all__'
        widgets = {
            'patient': forms.Select(attrs={'class': 'form-control'}),
            'drug_name': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'taken_time1': forms.Select(attrs={'class': 'form-control'}),
            'taken_time2': forms.Select(attrs={'class': 'form-control'}),
            'taken_time3': forms.Select(attrs={'class': 'form-control'}),
            'start_date': forms.DateInput(attrs={'class': 'form-control'},format='%Y-%m-%d'),
            'end_date': forms.DateInput(attrs={'class': 'form-control'}, format='%Y-%m-%d'),
        }
        labels = {
            'patient': 'Patient Name',
            'drug_name': 'Medicine Name',
            'taken_time1': 'Taken Time1',
            'taken_time2': 'Taken Time2',
            'taken_time3': 'Taken Time3',
        }    

healthapp/api/views.py
from rest_framework import viewsets
from healthapp.models import Doctor, Patient, Prescription
from .serializers import DoctorSerializer, PatientSerializer, PrescriptionSerializer

class DoctorViewSet(viewsets.ModelViewSet):
    queryset = Doctor.objects.all()
    serializer_class = DoctorSerializer

class PatientViewSet(viewsets.ModelViewSet):
    queryset = Patient.objects.all()
    serializer_class = PatientSerializer

class PrescriptionViewSet(viewsets.ModelViewSet):
    queryset = Prescription.objects.all()
    serializer_class = PrescriptionSerializer

healthapp/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin,LoginRequiredMixin
from django.views.generic import CreateView,UpdateView,ListView,DetailView,DeleteView
from .models import Prescription,Doctor
from .forms import PrescriptionForm

    
class AddPrescription(CreateView):
    model = Prescription
    form_class = PrescriptionForm
    template_name = 'healthapp/add.html'
    success_url= reverse_lazy('healthapp:all_prescription') 
    
class AllPrescription(ListView):
    model = Prescription
    context_object_name = 'prescription'
    template_name = 'healthapp/all.html'  
    
class UpdatePrescription(UpdateView):
    model = Prescription
    form_class = PrescriptionForm
    template_name = 'healthapp/update.html'
    success_url= reverse_lazy('healthapp:all_prescription') 
    
class ViewPrescription(DetailView):
    model = Prescription
    context_object_name = 'prescription'
    template_name = 'healthapp/view.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['doctor_object'] = Doctor.objects.get(pk=1)
        # Add more context objects as needed

        return context
    
class DeletePrescription(DeleteView):
    model = Prescription 
    template_name = 'healthapp/prescription_confirm_delete.html' 
    success_url= reverse_lazy('healthapp:all_prescription')     
      

healthapp/templates/healthapp/add.html
{% extends 'doctorPanel/docpanel.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
   <div class="row">
      <div class="col-12">
         <div class="page-title-box">
            <div class="clearfix"></div>
         </div>
      </div>
   </div>
   <div class="row">
      <div class="col-lg-12">
         <div class="card">
            <form method="POST">
               {% csrf_token %} 
               <div class="card-header ">
                  <div class="row">
                     <div class="col-md-8 card_header_title">
                        <i class="fab fa-gg-circle"></i>
                        Add Prescription
                     </div>
                     <div class="col-md-4 text-right card_header_btn">
                        <a class="btn btn-sm btn-secondary" href="{% url 'healthapp:all_prescription' %}">
                        <i class="fas fa-th fa-lg"></i>
                        All Prescription 
                        </a>
                     </div>
                  </div>
                  <div class="clr"></div>
               </div>
               <div class="card-body">
                  {{ form }}
               </div>
               <div class="card-footer text-center">

                  <div class="btn-group">
                     <button type="submit" class="btn btn-md btn-secondary">SAVE</button>
                  </div>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
{% endblock content %}

healthapp/templates/healthapp/all.html
{% extends 'doctorPanel/docpanel.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title"></h4>
                <div class="page-title-right">
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-8 card_header_title">
                            <i class="fab fa-gg-circle"></i>
                            All Prescription
                        </div>
                        <div class="col-md-4 text-right card_header_btn">
                            <a class="btn btn-sm btn-secondary" href="{% url 'healthapp:add_prescription' %}">
                                <i class="fa fa-plus-circle"></i>
                                Add Prescription
                            </a>
                        </div>
                    </div>
                    <div class="clr"></div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-12">
                            <table id="allTableInfo" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                                <thead class="">
                                    <tr>
                                        <th>Patient Name</th>
                                        <th>Medicine</th>
                                        <th>Start Date</th>
                                        <th>End Date</th>
                                        <th>Diagnostic Center</th>
                                        <th>Manage</th>
                                    </tr>
                                </thead>

                                <tbody>
                                {% for data in prescription %}
                                    <tr>
                                        <td>{{data.patient.patient_name}}</td>
                                        <td>{{data.drug_name}}</td>
                                        <td>{{data.start_date}}</td>
                                        <td>{{data.end_date}}</td>
                                        <td>{{data.patient.diagnostic_center}}</td>

                                        <td>
                                            <div class="btn-group dropdown">
                                                <button type="button" class="btn btn-secondary waves-effect">Manage</button>
                                                <button type="button" class="btn btn-dark dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="mdi mdi-chevron-down"></i>
                                                </button>
                                                <ul class="dropdown-menu">
                                                <li><a href="{% url 'healthapp:view_prescription' data.id %}" class="dropdown-item">View</a></li>
                                                <li><a href="{% url 'healthapp:update_prescription' data.id %}" class="dropdown-item">Edit</a></li>
                                                <li><a href="{% url 'healthapp:delete_prescription' data.id %}"class="dropdown-item">Delete</a></li>    
                                                </ul>
                                            </div>
                                        </td>
                                    </tr>
                                   {% endfor %}                        
                                
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <!-- <div class="btn-group">
                        <button type="button" class="btn btn-purple waves-effect">PRINT</button>
                        <button type="button" class="btn btn-dark waves-effect">PDF</button>
                        <button type="button" class="btn btn-pink waves-effect">EXEL</button>
                        <button type="button" class="btn btn-success waves-effect">CSV</button>
                    </div> -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

healthapp/templates/healthapp/healthapp_confirm_delete.html
{% extends 'healthAdmin/base.html' %}
{% load static %}
{% block content %}
<!-- Start Content-->
<div class="container-fluid">
   <div class="row">
      <div class="col-12">
         <div class="page-title-box">
            <!-- <h4 class="page-title"></h4>
            <div class="page-title-right">
               <ol class="breadcrumb p-0 m-0">
                  <li class="breadcrumb-item"><a href="#"></a></li>
                  <li class="breadcrumb-item"><a href="#"></a></li>
                  <li class="breadcrumb-item active"></li>
               </ol>
            </div> -->
            <div class="clearfix"></div>
         </div>
      </div>
   </div>
   <div class="row">
      <div class="col-lg-12">
         <div class="card">
            <form method="POST">
               {% csrf_token %} 
               <!-- <div class="card-header ">
                  <div class="row">
                     <div class="col-md-8 card_header_title">
                        <i class="fab fa-gg-circle"></i>
                        Add Department Information
                     </div>
                     <div class="col-md-4 text-right card_header_btn">
                        <a class="btn btn-sm btn-secondary" href="{% url 'department:department_all' %}">
                        <i class="fas fa-th fa-lg"></i>
                        All Course
                        </a>
                     </div>
                  </div>
                  <div class="clr"></div>
               </div>
               <div class="card-body"> -->
                  <!-- <div class="row">
                     <div class="col-md-1">
                     </div>
                     <div class="col-md-10">
                        <div class="alert alert-primary alert_primary" role="alert">
                        </div>
                        <div class="alert alert-danger alert-danger" role="alert">
                        </div>
                     </div>
                     <div class="col-md-1">
                     </div>
                  </div> -->
                  <!-- <div class="form-group row ">
                     <label class="col-sm-3 control-label control_label">Department Name<span class="req_star">*</span>:</label>
                     <div class="col-sm-7">
                        <input type="text" class="form-control form_control" name="name" id="name" value="" />
                        <span class="invalid-feedback" role="alert">
                        <strong></strong>
                        </span>
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="col-sm-3 control-label control_label">Description:</label>
                     <div class="col-sm-7">
                        <input type="text" class="form-control form_control" name="description" id="description" value="" />
                        <span class="invalid-feedback" role="alert">
                        <strong></strong>
                        </span>
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="col-sm-3 control-label control_label">Status:</label>
                     <div class="col-sm-7">
                        <input type="text" class="form-control form_control" name="status" id="status" value="" />
                        <span class="invalid-feedback" role="alert">
                        <strong></strong>
                        </span>
                     </div>
                  </div> -->
               </div>
               <div class="card-footer text-center">

                  <div class="btn-group">
                     <button type="submit" class="btn btn-md btn-secondary">Delete</button>
                  </div>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
{% endblock content %}

healthapp/templates/healthapp/update.html
{% extends 'doctorPanel/docpanel.html' %}
{% load static %}
{% block content %}
<!-- Start Content-->
<div class="container-fluid">
   <div class="row">
      <div class="col-12">
         <div class="page-title-box">
            <!-- <h4 class="page-title"></h4>
            <div class="page-title-right">
               <ol class="breadcrumb p-0 m-0">
                  <li class="breadcrumb-item"><a href="#"></a></li>
                  <li class="breadcrumb-item"><a href="#"></a></li>
                  <li class="breadcrumb-item active"></li>
               </ol>
            </div> -->
            <div class="clearfix"></div>
         </div>
      </div>
   </div>
   <div class="row">
      <div class="col-lg-12">
         <div class="card">
            <form method="POST">
               {% csrf_token %} 
               <div class="card-header ">
                  <div class="row">
                     <div class="col-md-8 card_header_title">
                        <i class="fab fa-gg-circle"></i>
                         Update Prescription
                     </div>
                     <div class="col-md-4 text-right card_header_btn">
                        <a class="btn btn-sm btn-secondary" href="{% url 'healthapp:all_prescription' %}">
                        <i class="fas fa-th fa-lg"></i>
                        All Prescription
                        </a>
                     </div>
                  </div>
                  <div class="clr"></div>
               </div>
               <div class="card-body">
                  <!-- <div class="row">
                     <div class="col-md-1">
                     </div>
                     <div class="col-md-10">
                        <div class="alert alert-primary alert_primary" role="alert">
                        </div>
                        <div class="alert alert-danger alert-danger" role="alert">
                        </div>
                     </div>
                     <div class="col-md-1">
                     </div>
                  </div> -->
                  <!-- <div class="form-group row ">
                     <label class="col-sm-3 control-label control_label">Department Name<span class="req_star">*</span>:</label>
                     <div class="col-sm-7">
                        <input type="text" class="form-control form_control" name="name" id="name" value="" />
                        <span class="invalid-feedback" role="alert">
                        <strong></strong>
                        </span>
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="col-sm-3 control-label control_label">Description:</label>
                     <div class="col-sm-7">
                        <input type="text" class="form-control form_control" name="description" id="description" value="" />
                        <span class="invalid-feedback" role="alert">
                        <strong></strong>
                        </span>
                     </div>
                  </div>
                  <div class="form-group row">
                     <label class="col-sm-3 control-label control_label">Status:</label>
                     <div class="col-sm-7">
                        <input type="text" class="form-control form_control" name="status" id="status" value="" />
                        <span class="invalid-feedback" role="alert">
                        <strong></strong>
                        </span>
                     </div>
                  </div> -->
                  {{form}}
               </div>
               <div class="card-footer text-center">

                  <div class="btn-group">
                     <button type="submit" class="btn btn-md btn-secondary">Update</button>
                  </div>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
{% endblock content %}

healthapp/templates/healthapp/view.html
{% extends 'doctorPanel/docpanel.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row">
       <div class="col-12">
          <div class="page-title-box">
             <div class="clearfix"></div>
          </div>
       </div>
    </div>
    <div class="row">
       <div class="col-lg-12">
          <div class="card">
             <div class="card-header">
                <div class="row">
                   <div class="col-md-8 card_header_title">
                      <i class="fab fa-gg-circle"></i>
                      View Prescription
                   </div>
                   <div class="col-md-4 text-right card_header_btn">
                      <a class="btn btn-sm btn-secondary" href="{% url 'healthapp:all_prescription' %}">
                      <i class="fa fa-plus-circle"></i>
                      All Prescription
                      </a>
                   </div>
                </div>
                <div class="clr"></div>
             </div>
             <div class="card-body">
                <div class="row">
                   <div class="col-md-2 col-sm-2 col-2"></div>
                   <div class="col-md-8 col-sm-8 col-8">
                      <table class="table table-bordered table-striped custom_view_table">
                        <tr>
                           <td>Patient Name</td>
                           <td>:</td>
                           <td>{{prescription.patient.patient_name}}</td>
                        </tr>
                        
                         <tr>
                            <td>Doctor Name</td>
                            <td>:</td>
                            <td>{{doctor_object.doctor_name}}</td>
                         </tr>
                         <tr>
                            <td>Medicine</td>
                            <td>:</td>
                            <td>
                                 {{prescription.drug_name}}
                            </td>
                         
                         </tr>
                      </table>
                   </div>
                   <div class="col-md-2 col-sm-2 col-2"></div>
                </div>
             </div>
             <div class="card-footer">
               <div class="row">
                  <div class="col-md-12 col-sm-12 col-12">
                      <table id="allTableInfo" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                          <thead class="">
                              <tr>
                                  <th>Medicine Taken Data Of Morning </th>
                                  <th>Medicine Taken Data Of Midday</th>
                                  <th>Medicine Taken Data Of Night</th>
                              </tr>
                          </thead>

                          <tbody>
                              <tr>
                                  <td>  
                                       <div class="iframe-container">
                                          <iframe scrolling="no" src="https://thingspeak.com/channels/2240587/charts/3?bgcolor=%23ffffff&color=%23d62020&dynamic=true&results=60&title=Piper+chaba+%28Chui%29&type=line"></iframe>
                                       </div><br>
                                       <div class="iframe-container">
                                          <iframe scrolling="no" src="https://thingspeak.com/channels/2240587/charts/3?bgcolor=%23ffffff&color=%23d62020&dynamic=true&results=60&title=Piper+chaba+%28Chui%29&type=line"></iframe>
                                       </div>
                                 </td>
                                  <td>
                                       <div class="iframe-container">
                                          <iframe scrolling="no" src="https://thingspeak.com/channels/2240587/charts/3?bgcolor=%23ffffff&color=%23d62020&dynamic=true&results=60&title=Piper+chaba+%28Chui%29&type=line"></iframe>
                                       </div><br>
                                       <div class="iframe-container">
                                          <iframe scrolling="no" src="https://thingspeak.com/channels/2240587/charts/3?bgcolor=%23ffffff&color=%23d62020&dynamic=true&results=60&title=Piper+chaba+%28Chui%29&type=line"></iframe>
                                       </div>
                                  </td>

                                  <td>
                                    <div class="iframe-container">
                                       <iframe scrolling="no" src="https://thingspeak.com/channels/2240587/charts/3?bgcolor=%23ffffff&color=%23d62020&dynamic=true&results=60&title=Piper+chaba+%28Chui%29&type=line"></iframe>
                                    </div><br>
                                    <div class="iframe-container">
                                       <iframe scrolling="no" src="https://thingspeak.com/channels/2240587/charts/3?bgcolor=%23ffffff&color=%23d62020&dynamic=true&results=60&title=Piper+chaba+%28Chui%29&type=line"></iframe>
                                    </div>
                                       
                                  </td>
                                  <td>
                                    
                                  </td>
                              </tr>                     
                          
                          </tbody>
                      </table>
                  </div>
              </div>
             </div>
          </div>
       </div>
    </div>
 </div>
{% endblock content %}