config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from healthapp import urls as healthurls
from healthAdmin import urls as dashboardurls
from doctorapp import urls as doctorurls
from patientapp import urls as patienturls
from doctorPanel import urls as docpanelurls

from rest_framework.routers import DefaultRouter
from healthapp.api.views import DoctorViewSet, PatientViewSet, PrescriptionViewSet

router = DefaultRouter()
router.register(r'doctors', DoctorViewSet)
router.register(r'patients', PatientViewSet)
router.register(r'prescriptions', PrescriptionViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('doctor/', include(healthurls, namespace='healthapp')),
    path('', include(dashboardurls, namespace='healthAdmin')),
    path('', include(docpanelurls, namespace='doctorPanel')),
    path('', include(doctorurls, namespace='doctorapp')),
    path('', include(patienturls, namespace='patientapp')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patientapp/urls.py
from django.urls import path
from patientapp.views import AddPatient,AllPatient,UpdatePatient,DeletePatient,ViewPatient


app_name='patientapp'

urlpatterns = [
    path('add-patient', AddPatient.as_view(), name="add_patient"),
    path('all-patient', AllPatient.as_view(), name="all_patient"),
    path('update-patient/<int:pk>', UpdatePatient.as_view(), name="update_patient"),
    path('view-patient/<int:pk>', ViewPatient.as_view(), name="view_patient"),
    path('delete-patient/<int:pk>', DeletePatient.as_view(), name="delete_patient"),
]

patientapp/models.py
from django.db import models

# Create your models here.

patientapp/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin,LoginRequiredMixin
from django.views.generic import CreateView,UpdateView,ListView,DetailView,DeleteView
from healthapp.models import Patient
from healthapp.forms import PatientForm
    
class AddPatient(CreateView):
    model = Patient
    form_class = PatientForm
    template_name = 'patientapp/add.html'
    success_url= reverse_lazy('patientapp:all_patient')    

class AllPatient(ListView):
    model = Patient
    context_object_name = 'patient'
    template_name = 'patientapp/all.html'  
    
class UpdatePatient(UpdateView):
    model = Patient
    form_class = PatientForm
    template_name = 'patientapp/update.html'
    success_url= reverse_lazy('patientapp:all_patient') 
    
class ViewPatient(DetailView):
    model = Patient
    context_object_name = 'patient'
    template_name = 'patientapp/view.html'
    
class DeletePatient(DeleteView):
    model = Patient 
    template_name = 'patientapp/patientapp_confirm_delete.html' 
    success_url= reverse_lazy('patientapp:all_patient')                    

patientapp/templates/patientapp/add.html
{% extends 'healthAdmin/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
   <div class="row">
      <div class="col-12">
         <div class="page-title-box">
            <div class="clearfix"></div>
         </div>
      </div>
   </div>
   <div class="row">
      <div class="col-lg-12">
         <div class="card">
            <form method="POST">
               {% csrf_token %} 
               <div class="card-header ">
                  <div class="row">
                     <div class="col-md-8 card_header_title">
                        <i class="fab fa-gg-circle"></i>
                        Add Patient Information
                     </div>
                     <div class="col-md-4 text-right card_header_btn">
                        <a class="btn btn-sm btn-secondary" href="{% url 'patientapp:all_patient' %}">
                        <i class="fas fa-th fa-lg"></i>
                        All Patient
                        </a>
                     </div>
                  </div>
                  <div class="clr"></div>
               </div>
               <div class="card-body">
                  {{ form }}
               </div>
               <div class="card-footer text-center">

                  <div class="btn-group">
                     <button type="submit" class="btn btn-md btn-secondary">SAVE</button>
                  </div>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
{% endblock content %}

patientapp/templates/patientapp/all.html
{% extends 'healthAdmin/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title"></h4>
                <div class="page-title-right">
                    <!-- <ol class="breadcrumb p-0 m-0">
                        <li class="breadcrumb-item"><a href="#"></a></li>
                        <li class="breadcrumb-item"><a href="#"></a></li>
                        <li class="breadcrumb-item active"></li>
                    </ol> -->
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-8 card_header_title">
                            <i class="fab fa-gg-circle"></i>
                            All Patient Information
                        </div>
                        <div class="col-md-4 text-right card_header_btn">
                            <a class="btn btn-sm btn-secondary" href="{% url 'patientapp:add_patient' %}">
                                <i class="fa fa-plus-circle"></i>
                                Add Patient
                            </a>
                        </div>
                    </div>
                    <div class="clr"></div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-12">
                            <table id="allTableInfo" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                                <thead class="">
                                    <tr>
                                        <th>Patient Id</th>
                                        <th>Patient Name</th>
                                        <th>Doctor Name</th>
                                        <th>Age</th>
                                        <th>Gender</th>
                                        <th>Height</th>
                                        <th>Weight</th>
                                        <th>Categori</th>
                                        <th>Contact</th>
                                        <th>Diagnostic</th>
                                        <th>Manage</th>
                                    </tr>
                                </thead>

                                <tbody>
                                {% for data in patient %}
                                    <tr>
                                        <td>{{data.patient_id}}</td>
                                        <td>{{data.patient_name}}</td>
                                        <td>{{data.doctor_id.doctor_name}}</td>
                                        <td>{{data.age}}</td>
                                        <td>{{data.gender}}</td>
                                        <td>{{data.height}}</td>
                                        <td>{{data.weight}}</td>
                                        <td>{{data.patient_category}}</td>
                                        <td>{{data.contact_number}}</td>
                                        <td>{{data.diagnostic_center}}</td>

                                        <td>
                                            <div class="btn-group dropdown">
                                        <button type="button" class="btn btn-secondary waves-effect">Manage</button>
                                        <button type="button" class="btn btn-dark dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="mdi mdi-chevron-down"></i>
                                        </button>
                                        <ul class="dropdown-menu">
                                        <li><a href="{% url 'patientapp:view_patient' data.id %}" class="dropdown-item">View</a></li>
                                        <li><a href="{% url 'patientapp:update_patient' data.id %}" class="dropdown-item">Edit</a></li>
                                        <li><a href="{% url 'patientapp:delete_patient' data.id %}"class="dropdown-item">Delete</a></li>    
                                        </ul>
                                        </div>
                                        </td>
                                    </tr>
                                   {% endfor %}                        
                                
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <!-- <div class="btn-group">
                        <button type="button" class="btn btn-purple waves-effect">PRINT</button>
                        <button type="button" class="btn btn-dark waves-effect">PDF</button>
                        <button type="button" class="btn btn-pink waves-effect">EXEL</button>
                        <button type="button" class="btn btn-success waves-effect">CSV</button>
                    </div> -->
                </div>
            </div>
        </div>
    </div>
    <!--delete model code start-->
    <!-- <div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <form method="post" action="#">
        
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="myModalLabel"><i class="fab fa-gg-circle"></i> Confirm Message</h5>
                    </div>
                    <div class="modal-body modal_body">
                        Are you sure to delete this information?
                        <input type="hidden" name="modal_id" id="modalID" value="" />
                    </div>
                    <div class="modal-footer modal_footer">
                        <button type="button" class="btn btn-sm btn-success waves-effect" data-dismiss="modal">No</button>
                        <button type="submit" class="btn btn-sm btn-danger waves-effect waves-light">Yes</button>
                    </div>
                </div>
            </form>
        </div>
    </div> -->
</div>
{% endblock content %}

patientapp/templates/patientapp/patientapp_confirm_delete.html
{% extends 'healthAdmin/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
   <div class="row">
      <div class="col-12">
         <div class="page-title-box">
            <div class="clearfix"></div>
         </div>
      </div>
   </div>
   <div class="row">
      <div class="col-lg-12">
         <div class="card">
            <form method="POST">
               {% csrf_token %} 
               </div>
               <div class="card-footer text-center">

                  <div class="btn-group">
                     <button type="submit" class="btn btn-md btn-secondary">Delete</button>
                  </div>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
{% endblock content %}

patientapp/templates/patientapp/update.html
{% extends 'healthAdmin/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
   <div class="row">
      <div class="col-12">
         <div class="page-title-box">
            <div class="clearfix"></div>
         </div>
      </div>
   </div>
   <div class="row">
      <div class="col-lg-12">
         <div class="card">
            <form method="POST">
               {% csrf_token %} 
               <div class="card-header ">
                  <div class="row">
                     <div class="col-md-8 card_header_title">
                        <i class="fab fa-gg-circle"></i>
                         Update Patient Information
                     </div>
                     <div class="col-md-4 text-right card_header_btn">
                        <a class="btn btn-sm btn-secondary" href="{% url 'patientapp:all_patient' %}">
                        <i class="fas fa-th fa-lg"></i>
                        All Patient
                        </a>
                     </div>
                  </div>
                  <div class="clr"></div>
               </div>
               <div class="card-body">
                  {{form}}
               </div>
               <div class="card-footer text-center">

                  <div class="btn-group">
                     <button type="submit" class="btn btn-md btn-secondary">Update</button>
                  </div>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
{% endblock content %}

patientapp/templates/patientapp/view.html
{% extends 'healthAdmin/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row">
       <div class="col-12">
          <div class="page-title-box">
             <div class="clearfix"></div>
          </div>
       </div>
    </div>
    <div class="row">
       <div class="col-lg-12">
          <div class="card">
             <div class="card-header">
                <div class="row">
                   <div class="col-md-8 card_header_title">
                      <i class="fab fa-gg-circle"></i>
                      View Patient Information
                   </div>
                   <div class="col-md-4 text-right card_header_btn">
                      <a class="btn btn-sm btn-secondary" href="{% url 'patientapp:all_patient' %}">
                      <i class="fa fa-plus-circle"></i>
                      All Patient
                      </a>
                   </div>
                </div>
                <div class="clr"></div>
             </div>
             <div class="card-body">
                <div class="row">
                   <div class="col-md-2 col-sm-2 col-2"></div>
                   <div class="col-md-8 col-sm-8 col-8">
                      <table class="table table-bordered table-striped custom_view_table">
                        <tr>
                           <td>Patient Id</td>
                           <td>:</td>
                           <td>{{patient.patient_id}}</td>
                        </tr>
                         <tr>
                            <td>Patient Name</td>
                            <td>:</td>
                            <td>{{patient.patient_name}}</td>
                         </tr>
                         <tr>
                            <td>Category</td>
                            <td>:</td>
                            <td>{{patient.patient_category}}</td>
                         </tr>
                         <tr>
                            <td>Doctor Name</td>
                            <td>:</td>
                            <td>{{patient.doctor_id.doctor_name}}</td>
                         </tr>
                         <tr>
                            <td>Department Designation</td>
                            <td>:</td>
                            <td>
                              {{patient.doctor_id.doctor_designation}}
                            </td>
                        
                         </tr>
                      </table>
                      
                   </div>
                 
                 <div class="iframe-container">
                  <iframe scrolling="no" src="https://thingspeak.com/channels/2240587/charts/3?bgcolor=%23ffffff&color=%23d62020&dynamic=true&results=60&title=Piper+chaba+%28Chui%29&type=line"></iframe>
              </div>
                   <div class="col-md-2 col-sm-2 col-2"></div>
                </div>
             </div>
             <div class="card-footer">
                <!-- <div class="btn-group">
                   <button type="button" class="btn btn-purple waves-effect">PRINT</button>
                   <button type="button" class="btn btn-dark waves-effect">PDF</button>
                   <button type="button" class="btn btn-pink waves-effect">EXEL</button>
                   <button type="button" class="btn btn-success waves-effect">CSV</button>
                </div> -->
             </div>
          </div>
       </div>
    </div>
 </div>
{% endblock content %}