config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from healthapp import urls as healthurls
from healthAdmin import urls as dashboardurls
from doctorapp import urls as doctorurls
from patientapp import urls as patienturls
from doctorPanel import urls as docpanelurls

from rest_framework.routers import DefaultRouter
from healthapp.api.views import DoctorViewSet, PatientViewSet, PrescriptionViewSet

router = DefaultRouter()
router.register(r'doctors', DoctorViewSet)
router.register(r'patients', PatientViewSet)
router.register(r'prescriptions', PrescriptionViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('doctor/', include(healthurls, namespace='healthapp')),
    path('', include(dashboardurls, namespace='healthAdmin')),
    path('', include(docpanelurls, namespace='doctorPanel')),
    path('', include(doctorurls, namespace='doctorapp')),
    path('', include(patienturls, namespace='patientapp')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctorapp/urls.py
from django.urls import path
from .views import AddDoctor,AllDoctor,UpdateDoctor,ViewDoctor,DeleteDoctor


app_name='doctorapp'

urlpatterns = [
    path('add-doctor', AddDoctor.as_view(), name="add_doctor"),
    path('all-doctor', AllDoctor.as_view(), name="all_doctor"),
    path('update-doctor/<int:pk>', UpdateDoctor.as_view(), name="update_doctor"),
    path('view-doctor/<int:pk>', ViewDoctor.as_view(), name="view_doctor"),
    path('delete-doctor/<int:pk>', DeleteDoctor.as_view(), name="delete_doctor"),
]

doctorapp/models.py
from django.db import models

# Create your models here.

doctorapp/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin,LoginRequiredMixin
from django.views.generic import CreateView,UpdateView,ListView,DetailView,DeleteView
from healthapp.models import Doctor
from healthapp.forms import DoctorForm
    
class AddDoctor(CreateView):
    model = Doctor
    form_class = DoctorForm
    template_name = 'doctorapp/add.html'
    success_url= reverse_lazy('doctorapp:add_doctor')  
    
class AllDoctor(ListView):
    model = Doctor
    context_object_name = 'doctor'
    template_name = 'doctorapp/all.html'  
    
class UpdateDoctor(UpdateView):
    model = Doctor
    form_class = DoctorForm
    template_name = 'doctorapp/update.html'
    success_url= reverse_lazy('doctorapp:all_doctor') 
    
class ViewDoctor(DetailView):
    model = Doctor
    context_object_name = 'doctor_obj'
    template_name = 'doctorapp/view.html'
    success_url= reverse_lazy('doctorapp:all_doctor') 
    
class DeleteDoctor(DeleteView):
    model = Doctor 
    template_name = 'doctorapp/doctorapp_confirm_delete.html' 
    success_url= reverse_lazy('doctorapp:all_doctor')                    

doctorapp/templates/doctorapp/add.html
{% extends 'healthAdmin/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
   <div class="row">
      <div class="col-12">
         <div class="page-title-box">
            <div class="clearfix"></div>
         </div>
      </div>
   </div>
   <div class="row">
      <div class="col-lg-12">
         <div class="card">
            <form method="POST">
               {% csrf_token %} 
               <div class="card-header ">
                  <div class="row">
                     <div class="col-md-8 card_header_title">
                        <i class="fab fa-gg-circle"></i>
                        Add Doctor Information
                     </div>
                     <div class="col-md-4 text-right card_header_btn">
                        <a class="btn btn-sm btn-secondary" href="{% url 'doctorapp:all_doctor' %}">
                        <i class="fas fa-th fa-lg"></i>
                        All Doctors
                        </a>
                     </div>
                  </div>
                  <div class="clr"></div>
               </div>
               <div class="card-body">
                  {{ form }}
               </div>
               <div class="card-footer text-center">

                  <div class="btn-group">
                     <button type="submit" class="btn btn-md btn-secondary">SAVE</button>
                  </div>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
{% endblock content %}

doctorapp/templates/doctorapp/all.html
{% extends 'healthAdmin/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title"></h4>
                <div class="page-title-right">
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-8 card_header_title">
                            <i class="fab fa-gg-circle"></i>
                            All Doctor Information
                        </div>
                        <div class="col-md-4 text-right card_header_btn">
                            <a class="btn btn-sm btn-secondary" href="{% url 'doctorapp:add_doctor' %}">
                                <i class="fa fa-plus-circle"></i>
                                Add Doctor
                            </a>
                        </div>
                    </div>
                    <div class="clr"></div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-12">
                            <table id="allTableInfo" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                                <thead class="">
                                    <tr>
                                        <th>Doctor Id </th>
                                        <th>Doctor Name</th>
                                        <th>Designation</th>
                                        <th>Contact Number</th>
                                        <th>Manage</th>
                                    </tr>
                                </thead>

                                <tbody>
                                {% for data in doctor %}
                                    <tr>
                                        <td>{{data.doctor_id}}</td>
                                        <td>{{data.doctor_name}}</td>
                                        <td>{{data.doctor_designation}}</td>
                                        <td>{{data.doctor_contact_number}}</td>

                                        <td>
                                            <div class="btn-group dropdown">
                                        <button type="button" class="btn btn-secondary waves-effect">Manage</button>
                                        <button type="button" class="btn btn-dark dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="mdi mdi-chevron-down"></i>
                                        </button>
                                        <ul class="dropdown-menu">
                                        <li><a href="{% url 'doctorapp:view_doctor' data.id %}" class="dropdown-item">View</a></li>
                                        <li><a href="{% url 'doctorapp:update_doctor' data.id %}" class="dropdown-item">Edit</a></li>
                                        <li><a href="{% url 'doctorapp:delete_doctor' data.id%}"class="dropdown-item">Delete</a></li>    
                                        </ul>
                                        </div>
                                        </td>
                                    </tr>
                                   {% endfor %}                        
                                
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <!-- <div class="btn-group">
                        <button type="button" class="btn btn-purple waves-effect">PRINT</button>
                        <button type="button" class="btn btn-dark waves-effect">PDF</button>
                        <button type="button" class="btn btn-pink waves-effect">EXEL</button>
                        <button type="button" class="btn btn-success waves-effect">CSV</button>
                    </div> -->
                </div>
            </div>
        </div>
    </div>
    <!--delete model code start-->
    <!-- <div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <form method="post" action="#">
        
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="myModalLabel"><i class="fab fa-gg-circle"></i> Confirm Message</h5>
                    </div>
                    <div class="modal-body modal_body">
                        Are you sure to delete this information?
                        <input type="hidden" name="modal_id" id="modalID" value="" />
                    </div>
                    <div class="modal-footer modal_footer">
                        <button type="button" class="btn btn-sm btn-success waves-effect" data-dismiss="modal">No</button>
                        <button type="submit" class="btn btn-sm btn-danger waves-effect waves-light">Yes</button>
                    </div>
                </div>
            </form>
        </div>
    </div> -->
</div>
{% endblock content %}

doctorapp/templates/doctorapp/doctorapp_confirm_delete.html
{% extends 'healthAdmin/base.html' %}
{% load static %}
{% block content %}
<!-- Start Content-->
<div class="container-fluid">
   <div class="row">
      <div class="col-12">
         <div class="page-title-box">
            <!-- <h4 class="page-title"></h4>
            <div class="page-title-right">
               <ol class="breadcrumb p-0 m-0">
                  <li class="breadcrumb-item"><a href="#"></a></li>
                  <li class="breadcrumb-item"><a href="#"></a></li>
                  <li class="breadcrumb-item active"></li>
               </ol>
            </div> -->
            <div class="clearfix"></div>
         </div>
      </div>
   </div>
   <div class="row">
      <div class="col-lg-12">
         <div class="card">
            <form method="POST">
               {% csrf_token %} 
               </div>
               <div class="card-footer text-center">

                  <div class="btn-group">
                     <button type="submit" class="btn btn-md btn-secondary">Delete</button>
                  </div>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
{% endblock content %}

doctorapp/templates/doctorapp/update.html
{% extends 'healthAdmin/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
   <div class="row">
      <div class="col-12">
         <div class="page-title-box">
            <div class="clearfix"></div>
         </div>
      </div>
   </div>
   <div class="row">
      <div class="col-lg-12">
         <div class="card">
            <form method="POST">
               {% csrf_token %} 
               <div class="card-header ">
                  <div class="row">
                     <div class="col-md-8 card_header_title">
                        <i class="fab fa-gg-circle"></i>
                         Update Doctor Information
                     </div>
                     <div class="col-md-4 text-right card_header_btn">
                        <a class="btn btn-sm btn-secondary" href="{% url 'doctorapp:all_doctor' %}">
                        <i class="fas fa-th fa-lg"></i>
                        All Doctors
                        </a>
                     </div>
                  </div>
                  <div class="clr"></div>
               </div>
               <div class="card-body">
                  {{form}}
               </div>
               <div class="card-footer text-center">

                  <div class="btn-group">
                     <button type="submit" class="btn btn-md btn-secondary">Update</button>
                  </div>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
{% endblock content %}

doctorapp/templates/doctorapp/view.html
{% extends 'healthAdmin/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row">
       <div class="col-12">
          <div class="page-title-box">

             <div class="clearfix"></div>
          </div>
       </div>
    </div>
    <div class="row">
       <div class="col-lg-12">
          <div class="card">
             <div class="card-header">
                <div class="row">
                   <div class="col-md-8 card_header_title">
                      <i class="fab fa-gg-circle"></i>
                      View Doctor Information
                   </div>
                   <div class="col-md-4 text-right card_header_btn">
                      <a class="btn btn-sm btn-secondary" href="{% url 'doctorapp:all_doctor' %}">
                      <i class="fa fa-plus-circle"></i>
                      All Doctors
                      </a>
                   </div>
                </div>
                <div class="clr"></div>
             </div>
             <div class="card-body">
                <div class="row">
                   <div class="col-md-2 col-sm-2 col-2"></div>
                   <div class="col-md-8 col-sm-8 col-8">
                      <table class="table table-bordered table-striped custom_view_table">
                        <tr>
                           <td>Doctor Id</td>
                           <td>:</td>
                           <td>{{doctor_obj.doctor_id}}</td>
                        </tr>
                         <tr>
                            <td>Doctor Name</td>
                            <td>:</td>
                            <td>{{doctor_obj.doctor_name}} </td>
                         </tr>
                         <tr>
                            <td>Designation</td>
                            <td>:</td>
                            <td>{{doctor_obj.doctor_designation}}</td>
                         </tr>
                         <tr>
                            <td>Contact No</td>
                            <td>:</td>
                            <td>{{doctor_obj.doctor_contact_number}}</td>
                         </tr>
                        
                      </table>
                   </div>
                   <div class="col-md-2 col-sm-2 col-2"></div>
                </div>
             </div>
             <div class="card-footer">
                <!-- <div class="btn-group">
                   <button type="button" class="btn btn-purple waves-effect">PRINT</button>
                   <button type="button" class="btn btn-dark waves-effect">PDF</button>
                   <button type="button" class="btn btn-pink waves-effect">EXEL</button>
                   <button type="button" class="btn btn-success waves-effect">CSV</button>
                </div> -->
             </div>
          </div>
       </div>
    </div>
 </div>
{% endblock content %}