config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from healthapp import urls as healthurls
from healthAdmin import urls as dashboardurls
from doctorapp import urls as doctorurls
from patientapp import urls as patienturls
from doctorPanel import urls as docpanelurls

from rest_framework.routers import DefaultRouter
from healthapp.api.views import DoctorViewSet, PatientViewSet, PrescriptionViewSet

router = DefaultRouter()
router.register(r'doctors', DoctorViewSet)
router.register(r'patients', PatientViewSet)
router.register(r'prescriptions', PrescriptionViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('doctor/', include(healthurls, namespace='healthapp')),
    path('', include(dashboardurls, namespace='healthAdmin')),
    path('', include(docpanelurls, namespace='doctorPanel')),
    path('', include(doctorurls, namespace='doctorapp')),
    path('', include(patienturls, namespace='patientapp')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctorPanel/urls.py
from django.urls import path

from doctorPanel.views import doctorpanel

app_name='doctorPanel'

urlpatterns = [
    path('doc-panel', doctorpanel, name="doc_panel"),
    # path('profile/<int:pk>', UserProfileDetailView.as_view(), name='profile_page'),
    # path('login/', login_view, name='login_page'),
    # path('logout/', logoutuser, name='logout_page'),
]

doctorapp/urls.py
from django.urls import path
from .views import AddDoctor,AllDoctor,UpdateDoctor,ViewDoctor,DeleteDoctor


app_name='doctorapp'

urlpatterns = [
    path('add-doctor', AddDoctor.as_view(), name="add_doctor"),
    path('all-doctor', AllDoctor.as_view(), name="all_doctor"),
    path('update-doctor/<int:pk>', UpdateDoctor.as_view(), name="update_doctor"),
    path('view-doctor/<int:pk>', ViewDoctor.as_view(), name="view_doctor"),
    path('delete-doctor/<int:pk>', DeleteDoctor.as_view(), name="delete_doctor"),
]

healthAdmin/urls.py
from django.urls import path

from healthAdmin.views import dashboard

app_name='healthAdmin'

urlpatterns = [
	path('', dashboard, name="dashboard"),
    # path('profile/<int:pk>', UserProfileDetailView.as_view(), name='profile_page'),
    # path('login/', login_view, name='login_page'),
    # path('logout/', logoutuser, name='logout_page'),
]

healthapp/urls.py
from django.urls import path
from .views import AddPrescription,AllPrescription,ViewPrescription,UpdatePrescription,DeletePrescription


app_name='healthapp'

urlpatterns = [
    path('add-prescription', AddPrescription.as_view(), name="add_prescription"),
     path('all-prescription', AllPrescription.as_view(), name="all_prescription"),
    path('update-prescription/<int:pk>', UpdatePrescription.as_view(), name="update_prescription"),
    path('view-prescription/<int:pk>', ViewPrescription.as_view(), name="view_prescription"),
    path('delete-prescription/<int:pk>', DeletePrescription.as_view(), name="delete_prescription"),
    
]

patientapp/urls.py
from django.urls import path
from patientapp.views import AddPatient,AllPatient,UpdatePatient,DeletePatient,ViewPatient


app_name='patientapp'

urlpatterns = [
    path('add-patient', AddPatient.as_view(), name="add_patient"),
    path('all-patient', AllPatient.as_view(), name="all_patient"),
    path('update-patient/<int:pk>', UpdatePatient.as_view(), name="update_patient"),
    path('view-patient/<int:pk>', ViewPatient.as_view(), name="view_patient"),
    path('delete-patient/<int:pk>', DeletePatient.as_view(), name="delete_patient"),
]

healthAdmin/models.py
from django.db import models

# Create your models here.

healthAdmin/views.py
from django.shortcuts import render
from healthapp.models import Patient,Prescription,Doctor

# Create your views here.
def dashboard(request):
    patient = Patient.objects.all()
    patient_count = patient.count()
    prescription = Prescription.objects.all()
    prescription_count =prescription.count()
    doctor = Doctor.objects.all()
    doctor_count = doctor.count()
    response = {
        'patient':patient_count,
        'prescription':prescription_count,
        'doctor': doctor_count
    }
    return render(request, 'healthAdmin/index.html',response)

healthAdmin/templates/healthAdmin/base.html
<!DOCTYPE html>
<html lang="en">
   {% load static %}
   <head>
      <meta charset="utf-8" />
      <title>{% block title %} {%endblock title%}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta content="Responsive bootstrap 4 admin template" name="description" />
      <meta content="Coderthemes" name="author" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <!-- Table datatable css -->
      <link href="{% static 'assets/libs/datatables/dataTables.bootstrap4.min.css'%}" rel="stylesheet" type="text/css" />
      <link href="{% static 'assets/libs/datatables/buttons.bootstrap4.min.css'%}" rel="stylesheet" type="text/css" />
      <link href="{% static 'assets/libs/datatables/fixedHeader.bootstrap4.min.html'%}" rel="stylesheet" type="text/css" />
      <link href="{% static 'assets/libs/datatables/responsive.bootstrap4.min.css'%}" rel="stylesheet" type="text/css" />
      <link href="{% static 'assets/libs/datatables/scroller.bootstrap4.min.css'%}" rel="stylesheet" type="text/css" />
      <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico'%}">
      <link href="{% static 'assets/libs/sweetalert2/sweetalert2.min.css'%}" rel="stylesheet" type="text/css" />
      <link href="{% static 'assets/css/bootstrap.min.css'%}" rel="stylesheet" type="text/css" id="bootstrap-stylesheet" />
      <link href="{% static 'assets/css/icons.min.css'%}" rel="stylesheet" type="text/css" />
      <link href="{% static 'assets/css/app.min.css'%}" rel="stylesheet" type="text/css" id="app-stylesheet" />
      <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
   </head>
   <body>
      <div id="wrapper">
         <div class="navbar-custom" style="background-color: darkgray;">
         </div>
         <div class="left-side-menu">
            <div class="slimscroll-menu">
               <div id="sidebar-menu">
                  <div class="user-box">
                     <div class="float-left">
                         <img src="{% static 'images/doc.png'%}" alt="" class="avatar-md rounded-circle">
                     </div>
                     <div class="user-info">
                         <div class="dropdown">
                             <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                     <i class="mdi mdi-chevron-down"></i>
                                                     Mithu
                                             </a>
                                             
                              <ul class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 29px, 0px); top: 0px; left: 0px; will-change: transform;">
                                 <li><a href="" class="dropdown-item"><i class="mdi mdi-face-profile mr-2"></i> Profile<div class="ripple-wrapper"></div></a></li>
                                 <li><a href="" class="dropdown-item"><i class="mdi mdi-power-settings mr-2"></i> Logout</a></li>
                              </ul>    
                         </div>
                         <p class="font-13 text-muted m-0">Administrator</p>
                     </div>
                     </div>
                  <br>
                  <ul class="metismenu" id="side-menu">
                     <li>
                        <a href="{% url 'healthAdmin:dashboard' %}" class="waves-effect">
                        <i class="mdi mdi-home"></i>
                        <span> Dashboard </span>
                        </a>
                     </li>
                     <li>
                        <a href="{% url 'doctorapp:all_doctor' %}" class="waves-effect">
                        <i class=" ion ion-md-cube"></i>
                        <span>Doctor</span>                     
                        </a>
                     </li>
                     <li>
                        <a href="{% url 'doctorPanel:doc_panel' %}" class="waves-effect">
                        <i class=" ion ion-md-options"></i>
                        <span>Doctor-Prescribe-Panel</span>                     
                        </a>
                     </li>
                     <li>
                        <a href="{% url 'patientapp:all_patient' %}" class="waves-effect">
                        <i class="ion ion-md-contacts"></i>
                        <span>Patient </span>                     
                        </a>
                     </li>
                     <!-- <li>
                        <a href="{% url 'healthapp:add_prescription' %}" class="waves-effect">
                        <i class=" ion ion-md-options"></i>
                        <span>Prescription </span>                     
                        </a>
                     </li> -->
               
                    
                     <li>
                        <a href="" class="waves-effect">
                        <i class=" fab fa-bandcamp"></i>
                        <span> LogOut  </span>
                        </a>
                     </li>
                  </ul>

               </div>
               <div class="clearfix"></div>
            </div>
         </div>
         <div class="content-page">
            <div class="content">
               
                  {% block content %}
                  {%endblock content%}
               
            </div>
            <footer class="footer">
               <div class="container-fluid">
                  <div class="row">
                     <div class="col-md-12">
                        Copyright © 2023-2024 Mithu | All Rights Reserved

                     </div>
                  </div>
               </div>
            </footer>
         </div>
      </div>
      <script>//datatable code start
         $('#datatable').dataTable( {
           "ordering": false,
           "searching": true,
         } );
         //message auto hide
         $(document).ready(function(){
           $('.alert_primary').fadeOut(5000);
         });
         
         </script>

      <script src="{% static 'assets/js/vendor.min.js'%}"></script>
      <script src="{% static 'assets/libs/moment/moment.min.js'%}"></script>
      <script src="{% static 'assets/libs/jquery-scrollto/jquery.scrollTo.min.js'%}"></script>
      <script src="{% static 'assets/libs/sweetalert2/sweetalert2.min.js'%}"></script>
      <script src="{% static 'assets/js/pages/jquery.chat.js'%}"></script>
      <script src="{% static 'assets/js/pages/jquery.todo.js'%}"></script>
      <script src="{% static 'assets/libs/flot-charts/jquery.flot.js'%}"></script>
      <script src="{% static 'assets/libs/flot-charts/jquery.flot.time.js'%}"></script>
      <script src="{% static 'assets/libs/flot-charts/jquery.flot.tooltip.min.js'%}"></script>
      <script src="{% static 'assets/libs/flot-charts/jquery.flot.resize.js'%}"></script>
      <script src="{% static 'assets/libs/flot-charts/jquery.flot.pie.js'%}"></script>
      <script src="{% static 'assets/libs/flot-charts/jquery.flot.selection.js'%}"></script>
      <script src="{% static 'assets/libs/flot-charts/jquery.flot.stack.js'%}"></script>
      <script src="{% static 'assets/libs/flot-charts/jquery.flot.crosshair.js'%}"></script>
      <!-- third party js -->
      <script src="{% static 'assets/libs/datatables/jquery.dataTables.min.js'%}"></script>
      <script src="{% static 'assets/libs/datatables/dataTables.bootstrap4.min.js'%}"></script>

      <script src="{% static 'assets/libs/datatables/dataTables.responsive.min.js'%}"></script>
      <script src="{% static 'assets/libs/datatables/responsive.bootstrap4.min.js'%}"></script>

      <script src="{% static 'assets/libs/datatables/dataTables.buttons.min.js'%}"></script>
      <script src="{% static 'assets/libs/datatables/buttons.bootstrap4.min.js'%}"></script>

      <script src="{% static 'assets/libs/jszip/jszip.min.js'%}"></script>
      <script src="{% static 'assets/libs/pdfmake/pdfmake.min.js'%}"></script>
      <script src="{% static 'assets/libs/pdfmake/vfs_fonts.js'%}"></script>

      <script src="{% static 'assets/libs/datatables/buttons.html5.min.js'%}"></script>
      <script src="{% static 'assets/libs/datatables/buttons.print.min.js'%}"></script>

      <script src="{% static 'assets/libs/datatables/dataTables.fixedHeader.min.html'%}"></script>
      <script src="{% static 'assets/libs/datatables/dataTables.keyTable.min.js'%}"></script>
      <script src="{% static 'assets/libs/datatables/dataTables.scroller.min.js'%}"></script>
      
      <!-- Dashboard init JS -->
      <script src="{% static 'assets/js/pages/dashboard.init.js'%}"></script>
        <!-- Datatables init -->
        <script src="{% static 'assets/js/pages/datatables.init.js'%}"></script>
      <!-- App js -->
      <script src="{% static 'assets/js/app.min.js'%}"></script>
      <script src="{% static 'js/custom.js'%}"></script>
   </body>
   <!-- Mirrored from coderthemes.com/moltran/layouts/blue-vertical/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 22 Feb 2021 12:04:25 GMT -->
</html>

healthAdmin/templates/healthAdmin/index.html
{% extends 'healthAdmin/base.html'%}
{% block content %}
      <div class="container-fluid">
         <!-- start page title -->
         <div class="row">
            <div class="col-12">
               <div class="page-title-box">
                  <!-- <h4 class="page-title"> </h4>
                  <div class="page-title-right">
                     <ol class="breadcrumb p-0 m-0">
                        <li class="breadcrumb-item"><a href="#"></a></li>
                        <li class="breadcrumb-item active"></li>
                     </ol>
                  </div> -->
                  <div class="clearfix"></div>
               </div>
            </div>
         </div>
         <!-- end page title -->
         <!--Widget-4 -->
         <div class="row">
            <div class="col-md-6 col-xl-3">
               <div class="card-box">
                  <div class="media">
                     <div class="avatar-md bg-secondary rounded-square mr-2">
                        <i class="ion ion-md-contacts avatar-title font-26 text-white"></i>
                     </div>
                     <div class="media-body align-self-center">
                        <div class="text-right">
                           <h4 class="font-20 my-0 font-weight-bold"><span data-plugin="counterup">{{doctor}}</span></h4>
                           <p class="mb-0 mt-1 text-truncate">Doctor</p>
                        </div>
                     </div>
                  </div>
                  <!-- <div class="mt-4">
                     <h6 class="text-uppercase">Target <span class="float-right">60%</span></h6>
                     <div class="progress progress-sm m-0">
                        <div class="progress-bar bg-info" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                           <span class="sr-only">60% Complete</span>
                        </div>
                     </div>
                  </div> -->
               </div>
               <!-- end card-box-->
            </div>
            <div class="col-md-6 col-xl-3">
               <div class="card-box">
                  <div class="media">
                     <div class="avatar-md bg-secondary rounded-square">
                        <i class=" ion ion-md-copy avatar-title font-26 text-white"></i>
                     </div>
                     <div class="media-body align-self-center">
                        <div class="text-right">
                           <h4 class="font-20 my-0 font-weight-bold"><span data-plugin="counterup">{{patient}}</span></h4>
                           <p class="mb-0 mt-1 text-truncate">Patient</p>
                        </div>
                     </div>
                  </div>
                  <!-- <div class="mt-4">
                     <h6 class="text-uppercase">Target <span class="float-right">90%</span></h6>
                     <div class="progress progress-sm m-0">
                        <div class="progress-bar bg-purple" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%">
                           <span class="sr-only">90% Complete</span>
                        </div>
                     </div>
                  </div> -->
               </div>
               <!-- end card-box-->
            </div>
            <div class="col-md-6 col-xl-3">
               <div class="card-box">
                  <div class="media">
                     <div class="avatar-md bg-secondary rounded-square">
                        <i class="fab fa-bandcamp avatar-title font-26 text-white"></i>
                     </div>
                     <div class="media-body align-self-center">
                        <div class="text-right">
                           <h4 class="font-20 my-0 font-weight-bold"><span data-plugin="counterup">{{prescription}}</span></h4>
                           <p class="mb-0 mt-1 text-truncate">Prescription</p>
                        </div>
                     </div>
                  </div>
         
               </div>
            </div>
            <div class="col-md-6 col-xl-3">
               <div class="card-box">
                  <div class="media">
                     <div class="avatar-md bg-secondary rounded-square">
                        <i class=" fas fa-user-alt avatar-title font-26 text-white"></i>
                     </div>
                     <div class="media-body align-self-center">
                        <div class="text-right">
                           <h4 class="font-20 my-0 font-weight-bold"><span data-plugin="counterup">0001</span></h4>
                           <p class="mb-0 mt-1 text-truncate">Administrator</p>
                        </div>
                     </div>
                  </div>
                  <!-- <div class="mt-4">
                     <h6 class="text-uppercase">Target <span class="float-right">60%</span></h6>
                     <div class="progress progress-sm m-0">
                        <div class="progress-bar bg-primary" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                           <span class="sr-only">60% Complete</span>
                        </div>
                     </div>
                  </div> -->
               </div>
               <!-- end card-box-->
            </div>
         </div>
         <!-- end row -->

{% endblock content %}

healthAdmin/templates/healthAdmin/login.html
<!DOCTYPE html>
<html lang="en">
   {% load static %}
   <!-- Mirrored from coderthemes.com/moltran/layouts/blue-vertical/pages-login.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 22 Feb 2021 12:05:14 GMT -->
   <head>
      <meta charset="utf-8" />
      <title>login</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta content="Responsive bootstrap 4 admin template" name="description" />
      <meta content="Coderthemes" name="author" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <!-- App favicon -->
      <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico'%}">
      <!-- App css -->
      <link href="{% static 'assets/css/bootstrap.min.css'%}" rel="stylesheet" type="text/css" id="bootstrap-stylesheet" />
      <link href="{% static 'assets/css/icons.min.css'%}" rel="stylesheet" type="text/css" />
      <link href="{% static 'assets/css/app.min.css'%}" rel="stylesheet" type="text/css" id="app-stylesheet" />
      <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
   </head>
   <body class="authentication-page">
      <div class="account-pages my-5">
         <div class="container">
            <div class="row justify-content-center">
               <!-- <div class="col-md-4 col-lg-6 col-xl-5"> -->
               <div class="col-md-4">
                  <div class="card mt-4">
                     <div class="card-header p-5 position-relative">
                        <div class="bg-overlay"></div>
                        <h4 class="text-white text-center mb-0">Attendance </h4>
                     </div>
                     <div class="card-body p-4 mt-2">
                        <form method="POST" action="#" class="p-2">
                           {% csrf_token %} 
                           <div class="form-group mb-3">
                              <input class="form-control" type="name" name="username" required="" placeholder="Username">
                           </div>
                           <div class="form-group mb-3">
                              <input class="form-control" type="password" name="password" required="" placeholder="Password">
                           </div>
                           <!-- <div class="form-group mb-3">
                              <div class="custom-control custom-checkbox">
                                 <input type="checkbox" class="custom-control-input" id="checkbox-signin">
                                 <label class="custom-control-label" for="checkbox-signin">Remember me</label>
                              </div>
                           </div> -->
                           <div class="form-group text-center mt-5 mb-4">
                              <button class="btn btn-primary waves-effect width-md waves-light" type="submit"> Log In </button>
                           </div>
                           <div class="form-group row mb-0">
                              <div class="col-sm-7">
                                 <!-- <a href="pages-recoverpw.html"><i class="fa fa-lock mr-1"></i> Forgot your password?</a> -->
                              </div>
                              <div class="col-sm-5 text-right">
                                 <!-- <a href="pages-register.html">Create an account</a> -->
                              </div>
                           </div>
                        </form>
                     </div>
                     <!-- end card-body -->
                  </div>
                  <!-- end card -->
                  <!-- end row -->
               </div>
               <!-- end col -->
            </div>
            <!-- end row -->
         </div>
      </div>
      <!-- Vendor js -->
      <script src="{% static 'assets/js/vendor.min.js'%}"></script>
      <!-- App js -->
      <script src="{% static 'assets/js/app.min.js'%}"></script>
   </body>
   <!-- Mirrored from coderthemes.com/moltran/layouts/blue-vertical/pages-login.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 22 Feb 2021 12:05:14 GMT -->
</html>

healthAdmin/templates/healthAdmin/profile.html
{% extends 'customAdmin/base.html'%}
{% block content %}
<div class="container-fluid">
    <div class="wraper">
        <div class="row">
            <!-- <div class="col-sm-12">
                <div class="bg-picture text-center" style="background-image:url('assets/images/big/bg.jpg')">
                    <div class="bg-picture-overlay"></div>
                    <div class="profile-info-name">
                        <img src="assets/images/users/avatar-1.jpg" class="avatar-xl rounded-circle img-thumbnail" alt="profile-image">
                        <h3 class="text-white">John Deon</h3>
                    </div>
                </div>
            </div> -->
        </div>

        <div class="row user-tabs">
            <div class="col-md-9 col-xl-6">
                <ul class="nav nav-tabs tabs-bordered nav-justified" role="tablist">
                    <li class="nav-item tab">
                        <a class="nav-link active" id="about-tab" data-toggle="tab" href="#about" role="tab" aria-controls="about" aria-selected="true">
                            <span class="d-block d-sm-none"><i class="fa fa-home"></i></span>
                            <span class="d-none d-sm-block">About Me</span>
                        </a>
                    </li>
                   
                </ul>
            </div>
            
        </div>
        <div class="row">
            <div class="col-lg-12">

                <div class="tab-content profile-tab-content">
                    <div class="tab-pane show active" id="about" role="tabpanel" aria-labelledby="about-tab">

                        <div class="row">
                            <div class="col-lg-4">
                                <!-- Personal-Information -->
                                <div class="card card-default card-fill">
                                    <div class="card-header">
                                        <h3 class="card-title">Personal Information</h3>
                                    </div>
                                    <div class="card-body">
                                        <div class="about-info-p">
                                            <strong>Full Name</strong>
                                            <br>
                                            <p class="text-muted"> {{ user.first_name }} {{ user.last_name }}</p>
                                        </div>
                                        <div class="about-info-p">
                                            <strong>Mobile</strong>
                                            <br>
                                            <p class="text-muted">{{ profile.phone }}</p>
                                        </div>
                                        <div class="about-info-p">
                                            <strong>Email</strong>
                                            <br>
                                            <p class="text-muted">{{profile.user.email}}</p>
                                        </div>
                                        <div class="about-info-p mb-0">
                                            <strong>Address</strong>
                                            <br>
                                            <p class="text-muted mb-0">{{ profile.address }}</p>
                                        </div>
                                    </div>
                                </div>
                                <!-- Personal-Information -->

                                <!-- Languages -->
                                <!-- <div class="card card-default card-fill">
                                    <div class="card-header">
                                        <h3 class="card-title">Languages</h3>
                                    </div>
                                    <div class="card-body">
                                        <ul class="mb-0">
                                            <li>English</li>
                                            <li>Franch</li>
                                            <li>Greek</li>
                                        </ul>
                                    </div>
                                </div> -->
                                <!-- Languages -->

                            </div>

                            
                            <div class="col-lg-8">
                                <!-- Personal-Information -->
                                <div class="card card-default card-fill">
                                    <div class="card-header">
                                        <h3 class="card-title">Biography</h3>
                                    </div>
                                    <div class="card-body">
                                        <p>{{ profile.bio }}</p>
                                    </div>
                                </div>
                                <!-- Personal-Information -->

                      

                            </div>

                        </div>
                    </div>

                
                </div>
            </div>
        </div>

    </div>
    <!-- end container-fluid -->

</div>
{% endblock content %}